### ISSUE TITLE
Add a VBS virus!

### ISSUE THREAD

**Issue by ghost** [rohitcoder/Virus-Store---batch-and-vbs-based-virus#1]
I have a virus download link: https://secufiles.com/anwH?pt=U0drdk5HRm5kSFZrVVZWMVJqSjJiRzh6TkRWSFVUMDlPZ2RscW9CK0NHSGZOL2Z1MmpHSnYxYz0%3D

**Comment by rohitcoder** [comment]
I would recommend you to Create a PR instead of random download links :)
